assembler.o: assembler.c utils.h Error_Handler.h
	gcc -ansi -pedantic -Wall -c assembler.c

PreProcessor.o: PreProcessor.c PreProcessor.h utils.h Error_Handler.h
	gcc -ansi -pedantic -Wall -c PreProcessor.c

Utils.o: Utils.c utils.h Error_Handler.h
	gcc -ansi -pedantic -Wall -c Utils.c

Error_Handler.o: Error_Handler.c Error_Handler.h Utils.h
	gcc -ansi -pedantic -Wall -c Error_Handler.c

data.o: data.c data.h Utils.h Error_Handler.h
	gcc -ansi -pedantic -Wall -c data.c
.PHONY: clean

clean:
	rm -f *.o